trigger:
- rasa-cmips_onecontainer

pr: none # This disables Pull Request (PR) triggers, you can adjust it if needed

stages:
- stage: BuildActions
  displayName: Build stage for rasacustomformsactions
  jobs:
  - job: BuildActions
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: 'rasacustomformsactions'
        dockerfile: '**/Dockerfile.test'
        containerRegistry: 'dee01d6c-2a10-48ac-b011-4c5630267cdc' # Use the appropriate connection
        tags: |
          $(Build.BuildId)

- stage: BuildNLU
  displayName: Build stage for rasacustomformsnlu
  jobs:
  - job: BuildNLU
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: 'rasacustomformsnlu'
        dockerfile: '**/Dockerfile.test'
        containerRegistry: 'b843bbb8-9286-45c2-90ec-3503cbc4f78e' # Use the appropriate connection
        tags: |
          $(Build.BuildId)

- stage: DeployToAKS
  displayName: Deploy to Azure Kubernetes Service
  dependsOn:
  - BuildActions
  - BuildNLU
  jobs:
  - job: DeployToAKS
    displayName: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: KubernetesManifest@0
      displayName: Create imagePullSecret for rasacustomformsactions
      inputs:
        action: createSecret
        secretName: 'x2container78551212-auth'
        dockerRegistryEndpoint: 'dee01d6c-2a10-48ac-b011-4c5630267cdc' # Use the appropriate connection

    - task: KubernetesManifest@0
      displayName: Deploy rasacustomformsactions to Kubernetes cluster
      inputs:
        action: deploy
        manifests: |
          $(Pipeline.Workspace)/manifests/deployment-actions.yml
          $(Pipeline.Workspace)/manifests/service-actions.yml
        imagePullSecrets: |
          x2container78551212-auth
        containers: |
          x2container.azurecr.io/rasacustomformsactions:$(Build.BuildId)

    - task: KubernetesManifest@0
      displayName: Create imagePullSecret for rasacustomformsnlu
      inputs:
        action: createSecret
        secretName: 'x2container15463cd1-auth'
        dockerRegistryEndpoint: 'b843bbb8-9286-45c2-90ec-3503cbc4f78e' # Use the appropriate connection

    - task: KubernetesManifest@0
      displayName: Deploy rasacustomformsnlu to Kubernetes cluster
      inputs:
        action: deploy
        manifests: |
          $(Pipeline.Workspace)/manifests/deployment.yaml
          $(Pipeline.Workspace)/manifests/service.yaml
        imagePullSecrets: |
          x2container15463cd1-auth
        containers: |
          x2container.azurecr.io/rasacustomformsnlu:$(Build.BuildId)
