trigger:
- rasa-cmips_onecontainer

pr: none # This disables Pull Request (PR) triggers, you can adjust it if needed

stages:
- stage: BuildAndDeploy
  displayName: Build and Deploy
  jobs:
  - job: BuildAndDeploy
    displayName: Build and Deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        # Build and push the Docker image for your common code
        docker build -t your-common-image:$(Build.BuildId) -f path/to/Dockerfile .
        docker login -u $(acrUsername) -p $(acrPassword) youracr.azurecr.io
        docker push youracr.azurecr.io/your-common-image:$(Build.BuildId)
      displayName: 'Build and Push Docker Image'
      env:
        ACR_NAME: youracr

    - task: KubernetesManifest@0
      displayName: Deploy your-common-image to Kubernetes cluster
      inputs:
        action: deploy
        manifests: |
          $(Pipeline.Workspace)/manifests/deployment-your-common-image.yml
          $(Pipeline.Workspace)/manifests/service-your-common-image.yml
        containers: |
          youracr.azurecr.io/your-common-image:$(Build.BuildId)
        imagePullSecrets: |
          youracr-auth

    - task: KubernetesManifest@0
      displayName: Deploy rasacustomformsactions to Kubernetes cluster
      inputs:
        action: deploy
        manifests: |
          $(Pipeline.Workspace)/manifests/deployment-actions.yml
          $(Pipeline.Workspace)/manifests/service-actions.yml
        imagePullSecrets: |
          x2container78551212-auth
        containers: |
          x2container.azurecr.io/rasacustomformsactions:$(Build.BuildId)

    - task: KubernetesManifest@0
      displayName: Deploy rasacustomformsnlu to Kubernetes cluster
      inputs:
        action: deploy
        manifests: |
          $(Pipeline.Workspace)/manifests/deployment.yaml
          $(Pipeline.Workspace)/manifests/service.yaml
        imagePullSecrets: |
          x2container15463cd1-auth
        containers: |
          x2container.azurecr.io/rasacustomformsnlu:$(Build.BuildId)

