FROM rasa/rasa:2.7.1

WORKDIR  /app

COPY . /app

RUN pip install -r requirements.txt

RUN pre-commit install

RUN python3 -m spacy download en_core_web_md

RUN python3 -m spacy link en_core_web_md en

COPY . .

RUN chmod 777 cmips_nlu.sh

RUN ls -ltr && pwd

ENTRYPOINT ["/app/cmips_nlu.sh"]

EXPOSE 5005
