apiVersion : apps/v1
kind: Deployment
metadata:
  name: onecontainer 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onecontainer
  template:
    metadata:
      labels:
        app: xresearchrasaone 
    spec:
      containers:
        - name: onecontainer 
          image: x2container.azurecr.io/onecontainer
          ports:
          - containerPort: 5005
          - containerPort: 5055
