apiVersion: apps/v1
kind: Deployment
metadata:
  name: rasacustomforms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rasaonecontainer
  template:
    metadata:
      labels:
        app: rasaonecontainer
    spec:
      containers:
        - name: rasacustomformsactions
          image: x2container.azurecr.io/rasacustomformsactions
          ports:
            - containerPort: 5055
          resources:
            requests:
              cpu: 200m
              memory: 1000Mi
            limits:
              cpu: 2000m
              memory: 1500Mi
        - name: rasacustomformsnlu
          image: x2container.azurecr.io/rasacustomformsnlu
          ports:
            - containerPort: 5005
          resources:
            requests:
              cpu: 200m
              memory: 2000Mi
            limits:
              cpu: 3500m
              memory: 4000Mi
