apiVersion : apps/v1
kind: Deployment
metadata:
  name: rasacustomformsnlu 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rasacustomformsnlu
  template:
    metadata:
      labels:
        app: rasacustomformsnlu 
    spec:
      containers:
        - name: rasacustomformsnlu 
          image: x2container.azurecr.io/rasacustomformsnlu
          ports:
          - containerPort: 5005
          resources:
            requests:
              cpu: 200m
              memory: 2000Mi
            limits:
              cpu: 3500m
              memory: 4000Mi
