apiVersion: v1
kind: Service
metadata:
    name: rasacustomformsactions
spec:
    type: LoadBalancer
    ports:
    - port: 5055 
    selector:
        app: rasacustomformsactions
---
apiVersion: v1
kind: Service
metadata:
    name: rasacustomformsnlu
spec:
    type: LoadBalancer
    ports:
    - port: 5005 
    selector:
        app: rasacustomformsnlu
