mongo_name: mongodb://cmipsmongo:fikVrBA9FqRICYLUM2UDnChoGxE7MiVtdVuANhtH9DCVlLcMUtRU6vLLPhbyLXc0dqJ0cEiKOBzvACDbIGPvZQ==@cmipsmongo.mongo.cosmos.azure.com:10255/?ssl=true&retrywrites=false&replicaSet=globaldb&maxIdleTimeMS=120000&appName=@cmipsmongo@
mongo_db: riva
mongo_collection : conversation